// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCP.App.Persistencia;

namespace UCP.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210914003432_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UCP.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Vehiculo_1id")
                        .HasColumnType("int");

                    b.Property<int?>("Vehiculo_2id")
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicionEspecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Vehiculo_1id");

                    b.HasIndex("Vehiculo_2id");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("UCP.App.Dominio.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("UCP.App.Dominio.Persona", b =>
                {
                    b.HasOne("UCP.App.Dominio.Vehiculo", "Vehiculo_1")
                        .WithMany()
                        .HasForeignKey("Vehiculo_1id");

                    b.HasOne("UCP.App.Dominio.Vehiculo", "Vehiculo_2")
                        .WithMany()
                        .HasForeignKey("Vehiculo_2id");

                    b.Navigation("Vehiculo_1");

                    b.Navigation("Vehiculo_2");
                });
#pragma warning restore 612, 618
        }
    }
}
